services:
  egg-production-inferential-test:
    image: paolode/egg-production-inferential-test:2fae3cd
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
